### ISSUE TITLE
Create parents as attribute

### ISSUE THREAD

**Issue by StefanCiesilski** [cityjson/cityjson-qgis-plugin#35]
Is it possible to pass the parent attribute in QGIS as an attribute when loading.
Otherwise I have entries and do not know which main entry they belong to.

  "CityObjects": {
    "UUID_fab50c6d-4cc0-45c7-ae1d-994de421c72c": {
      "type": "**BuildingPart**",
      "attributes": {
        "measuredHeight": 7.251,
        "creationDate": "2020-01-20",
        "DatenquelleDachhoehe": "1000",
        "Grundrissaktualitaet": "2020-01-01",
        "DatenquelleLage": "1000",
        "DatenquelleBodenhoehe": "1200",
        "BezugspunktDach": "1000"
      },
      "**parents**": [
        "DETHL57P0000QHJG"
      ],

[CityJson.zip](https://github.com/cityjson/cityjson-qgis-plugin/files/6390655/CityJson.zip)

**Comment by liberostelios** [comment]
Hi @StefanCiesilski 

Thanks for reporting this. That's a good point! I've missed that.

Will fix it asap.

**Comment by StefanCiesilski** [comment]
Thanks.
Do you know when approx.

**Comment by liberostelios** [comment]
Probably today. Otherwise, for sure by the end of the week.

**Comment by StefanCiesilski** [comment]
Thanks. Great

**Comment by liberostelios** [comment]
The version [0.7.0](https://github.com/cityjson/cityjson-qgis-plugin/releases/tag/v0.7.0) now supports parents and children.

**Comment by StefanCiesilski** [comment]
Hi @liberostelios 
I have test it. It works, but is it possible to create the Attribute without "['  ']"
![grafik](https://user-images.githubusercontent.com/50232158/116507230-2a7d3280-a8bf-11eb-948c-a688680058da.png)

The children id is not set.
And its possible if the parents id is NULL, to add the uid to parents id? So I can sort by a building.

**Comment by liberostelios** [comment]
For me `children` works fine, but there was an ambiguity regarding the field size so it might be fixed now. Which version of QGIS are you using?

Can you please try this version: [CityJSON-loader.zip](https://github.com/cityjson/cityjson-qgis-plugin/files/6397359/CityJSON-loader.zip)? If it works for you, I'll push it as version 0.7.1.

**Comment by StefanCiesilski** [comment]
I have test it. 
Parents id is correct. And children works also fine. 
![grafik](https://user-images.githubusercontent.com/50232158/116530219-14329f00-a8de-11eb-88bb-4a4afbf63bb1.png)

I have QGIS 3.18.0

How can I best sort it. So that all parts of the building stand one below the other.

**Comment by liberostelios** [comment]
Glad that it works. I've pushed this as version 0.7.1.

I am not sure if I can help you with your question. There is a way to setup relationships between different layers. I've tried setting a relationship between `parents` and `uuid` but QGIS crashed.

**Comment by StefanCiesilski** [comment]
I solved my problem.. 
I have create a new attribute "building". With field calculator copy "parents" into "buildings". They are still missing copy "uid" into "building" .
Is this possible by load the CityJSON file?

**Comment by liberostelios** [comment]
Sounds like a very specific case to me. I'd refrain from doing so, because this would introduce too much redundancy and end up creating data that are much altered compared to the initial file. Plus, `parents` is supposed to be an array and not a single value.

I don't get exactly what you did. Sounds to me like all you need is to copy the uuid in parents when it's null, right? So you can make it with this formula: `if ( "parents" is null, "uuid", "parents" )`. Then you can use this to sort. But this only works if you know you have one parent.

**Comment by StefanCiesilski** [comment]
that's true
Thank you anyway
